[package]
authors = ["YUUKIToriyama<github@toriyama.dev>"]
description = "Draw julia set on CanvasElement"
edition = "2021"
license = "MIT"
name = "draw-julia"
readme = "README.md"
repository = "https://github.com/YUUKIToriyama/draw-julia"
version = "0.2.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.59"
num-complex = "0.4.2"
wasm-bindgen = "0.2.82"
web-sys = {version = "0.3.59", features = ["CanvasRenderingContext2d", "ImageData", "HtmlCanvasElement"]}
